### ISSUE TITLE
Reboot after install to get icons. 

### ISSUE THREAD

**Issue by emiljoha** [paolorotolo/spotify-linux-installer#1] opened 2017-06-25 14:02 UTC
Had to do a reboot after installation to get the Spotify icon to show up. Running Tumbleweed. 

Would be nice to ether have a note of this in the instructions or a fix so that no reboot is needed. 

Awesome work!

**Comment by paolorotolo** [comment] 2017-06-25 15:32
Hey, thanks for the pull. I noticed we don't need a full reboot. If you're on GNOME, just press Alt+F2 and write `r`.

Also, there's a command to reload icon cache we could add the script: `gtk-update-icon-cache`. Since I'm unable to reproduce, can you test if the command fixes the issue without reboot?

Thanks.

**Comment by ghost** [comment] 2017-07-14 22:33
The bug has been resolved with the latest commit, or not?

_Sent from my Huawei VNS-L31 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by emiljoha** [comment] 2017-07-15 21:07
Sorry, missed the notification about the reply. 

Commit? I'm on mobile but I can't see a commit referenced in the thread... 

Will take a look tomorrow to see if I can reproduce it with old version and then test to see if this gtk-update-icon-cache solves the problem.

**Comment by paolorotolo** [comment] 2017-07-16 08:18
Thanks, I'm not able to reproduce the issue, so I can't help.
@nat13ejo keep us updated.

**Comment by emiljoha** [comment] 2017-07-16 11:01
This is my results after some tinkering. 

That command is already in the script here: 
https://github.com/paolorotolo/spotify-linux-installer/blob/2510e13a5ee920e8afd0c249d5763259422f61bd/install-spotify.sh#L56

However the command by itself does not evidently solve the problem. I have to run:
"sudo gtk-update-icon-cache --force /usr/share/icons/hicolor" 
to make it update the cache. As the cache file is only writable with root "sudo" is needed, and "--force" as it thinks that it already is up-to-date. 

And finally the PATH: 
"It expects to be given the PATH to a icon theme directory containing an index.theme, e.g. /usr/share/icons/hicolor, and writes a icon-theme.cache containing cached information about the icons in the directory tree below the given directory." 
- https://developer.gnome.org/gtk3/stable/gtk-update-icon-cache.html

There are two problems with this the first being the most important, 1) The command needing elevated privileges with one should not give to random scripts on the internet, and 2) The icon directory path might not be the same on all relevant distributions.

**Comment by emiljoha** [comment] 2017-07-19 16:01
There is a way to get around these two problems by linking/copying the index.theme file from /use/share/icons/hicolor to the $HOME$.local equivalent where the icon is saved.

Not sure if this is a reasonable solution.

**Comment by emiljoha** [comment] 2017-07-19 16:28
Of course then run the gtk-update-icon cache with the .local path as argument.

**Comment by megamaced** [comment] 2017-07-22 13:59
You should look into my code from Spotify-EasyRpm -noroot. Use xdg-desktop-menu as it does not require root

**Comment by megamaced** [comment] 2017-07-22 14:00
And xdg-desktop-icon but i didnt need this

**Comment by emiljoha** [comment] 2017-07-23 08:38
Thanks for the suggestion @megamaced. You are right that xdg-desktio-menu/-icon do not require root however the Spotify icon is still not shown after using them. Sometimes after using them it seemed like the shell restarted and the the icon was showed correctly but that was only occasional.

**Closed as completed** 2017-07-29 08:01 UTC
Labels: bug
